# Generated by Django 2.2 on 2020-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_size', models.IntegerField(default=0)),
                ('y_size', models.IntegerField(default=0)),
                ('crop_yield', models.CharField(default='', max_length=2500)),
                ('pasture_yield', models.CharField(default='', max_length=2500)),
                ('ore_yield', models.CharField(default='', max_length=2500)),
                ('wood_yield', models.CharField(default='', max_length=2500)),
                ('fresh_water', models.CharField(default='', max_length=2500)),
            ],
        ),
    ]
